# Site settings
title: Mehackit creative programming workshop with Sonic Pi
email: hello@mehackit.org
description: Creative programming workshop with Sonic Pi
description_fi: Musiikkiohjelmointia Sonic Pi -ohjelmalla
description_fr: Atelier de création musicale avec Sonic Pi
description_se: Musikprogrammering med Sonic Pi
description_no: Kreativ programmeringsworkshop med Sonic Pi
description_kr: Sonic Pi와 함께하는 음악 프로그래밍
description_es: Taller de programación creativa con Sonic Pi
description_ja: Sonic Piでクリエイティブ・プログラミング
baseurl: "/sonic-pi-workshop/" # the subpath of your site, e.g. /blog/
url: "https://kn1kn1.github.io/" # the base hostname & protocol for your site
# url : "http://127.0.0.1:4000"
twitter_username: mehackit
github_username:  ohss

# Build settings
markdown: kramdown

collections:
  exercises:
    output: true
